name: CI / lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - run: bundle config set without "production"
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rubocop --format progress
